sudo: required
dist: trusty
services:
  - docker

language: python

python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev

install:
    - docker pull bandrel/ocyara:latest
    - docker run --name travis -dt bandrel/ocyara:latest
    - docker cp /home/travis/build/bandrel/OCyara travis:/home # need to move this directory into the docker image for testing
    - docker exec travis bash -c "cd /home/OCyara && pip3 install -U -r requirements.txt"

script: 
  - docker exec travis bash -c "python3 -m pytest"
