sudo: required
 
language: python

python:
  - "3.5"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cython3 cython python3-dev tesseract-ocr libtesseract-dev libleptonica-dev libtesseract3
install: 
  - pip install yara-python
  - pip install pillow
  - pip install cython
  - CPPFLAGS=-I/usr/local/include pip3 install tesserocr
  - pip install pytest
  - pip install -r requirements.txt
# command to run tests
script: pytest  
