sudo: required
dist: trusty
language: python
services:
  - docker
env:
  - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6
install:
  - docker pull bandrel/ocyara:latest
  - docker run --name travis -dt bandrel/ocyara:latest
  - docker cp /home/travis/build/bandrel/OCyara travis:/home # need to move this directory into the docker image for testing

script: 
  - docker exec travis bash -c "source ${PYTHON_VERSION}/bin/activate && cd /home/OCyara && python -m pytest"
